### PR TITLE
Development to discuss

### PR DESCRIPTION
**Pull request by reinaortega**

### CODE REVIEW

**Comment by ankraft** [comment]
The second patch (continue subscription) is ok. The first one (continue deregistrtation) means that, no matter whether there was an error, deletions continue (what is good), but the method always return OK. Is this intended?

**Comment by reinaortega** [comment]
Thing is that I think that it is not an error. Default ACP is to be deleted but it may not have been created (if acpi was specified during the creation). Another solution could be to flag whether or not it was created

**Comment by ankraft** [comment]
Right. Let's add a flag that an ACP was created during AE registration. Then it is much easier to determine whether it should be deleted during AE de-registration.

**Comment by ankraft** [comment]
<div></div><div>Thing is that I think that it is not an error. Default ACP is to be deleted but it may not have been created (if acpi was specified during the creation). Another solution could be to flag whether or not it was created
<br/>
<br/>-- 
<br/>You are receiving this because you commented.
<br/>Reply to this email directly or view it on GitHub:
<br/>https://github.com/ankraft/ACME-oneM2M-CSE/pull/4#issuecomment-632559678</div>

**Pull request merged**
